[package]
name = "test2_rs"
version = "0.1.0"
authors = ["a3104 <a3104@example.com>"]
license = "Apache-2.0"

[dependencies]
serde = "1.0"
serde_json = "1.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
actions-rs-toolchain = "1.0"
